// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXwK168U539jntYAUPtPNPr5Loc6be2h4',
    appId: '1:78118865237:web:3b95bf28dc1b9d65b287dc',
    messagingSenderId: '78118865237',
    projectId: 'chat-app-dh',
    authDomain: 'chat-app-dh.firebaseapp.com',
    storageBucket: 'chat-app-dh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CCp3ct2HwbsdP0vR-h1sC_85F9ppp6A',
    appId: '1:78118865237:android:58c791c4e1357f57b287dc',
    messagingSenderId: '78118865237',
    projectId: 'chat-app-dh',
    storageBucket: 'chat-app-dh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIM_oPXNntw_Gt3zCgeyO6zQmRzV8BZ6M',
    appId: '1:78118865237:ios:d15cd95fdc6d583cb287dc',
    messagingSenderId: '78118865237',
    projectId: 'chat-app-dh',
    storageBucket: 'chat-app-dh.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIM_oPXNntw_Gt3zCgeyO6zQmRzV8BZ6M',
    appId: '1:78118865237:ios:8f87cac17b72d487b287dc',
    messagingSenderId: '78118865237',
    projectId: 'chat-app-dh',
    storageBucket: 'chat-app-dh.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
